from datetime import datetime
from typing import Optional
from pydantic.v1 import BaseModel

from py_ocsf_models.events.findings.severity_id import SeverityID
from py_ocsf_models.events.findings.status_id import StatusID
from py_ocsf_models.objects.enrichment import Enrichment
from py_ocsf_models.objects.metadata import Metadata
from py_ocsf_models.objects.observable import Observable
from py_ocsf_models.events.iam.activity_id import AuthenticationActivityID
from py_ocsf_models.events.iam.auth_protocol_id import AuthProtocolID
from py_ocsf_models.events.iam.category_uid import IAMCategoryUID
from py_ocsf_models.events.iam.class_uid import AuthenticationClassUID
from py_ocsf_models.events.iam.logon_type_id import LogonTypeID
from py_ocsf_models.events.iam.type_uid import AuthenticationTypeUID
from py_ocsf_models.objects.actor import Actor
from py_ocsf_models.objects.authentication_factor import AuthenticationFactor
from py_ocsf_models.objects.authentication_token import AuthenticationToken
from py_ocsf_models.objects.device import Device
from py_ocsf_models.objects.network_endpoint import NetworkEndpoint
from py_ocsf_models.objects.process import Process
from py_ocsf_models.objects.service import Service
from py_ocsf_models.objects.session import Session
from py_ocsf_models.objects.user import User


class Authentication(BaseModel):
    """
    Authentication events report authentication session activities, including user attempts to log on or log off, 
    regardless of success, as well as other key stages within the authentication process. These events are typically 
    generated by authentication services, such as Kerberos, OIDC, or SAML, and may include information about the user, 
    the authentication method used, and the status of the authentication attempt.

    Attributes:
    - Activity ID (activity_id) [Required]: The normalized identifier of the activity that triggered the event.
    - Activity Name (activity_name) [Optional]: The event activity name, as defined by the activity_id.
    - Actor (actor) [Recommended]: The actor object describes details about the user/role/process that was the source of the activity.
    - Authentication Factors (auth_factors) [Optional]: Describes a category of methods used for identity verification in an authentication attempt.
    - Auth Protocol (auth_protocol) [Recommended]: The authentication protocol as defined by the caption of auth_protocol_id.
    - Auth Protocol ID (auth_protocol_id) [Recommended]: The normalized identifier of the authentication protocol used to create the user session.
    - Authentication Token (authentication_token) [Optional]: The authentication token, ticket, or assertion, e.g. Kerberos, OIDC, SAML.
    - Category Name (category_name) [Optional]: The event category name: Identity & Access Management.
    - Category ID (category_uid) [Required]: The category unique identifier of the event.
    - Certificate (certificate) [Recommended]: The certificate associated with the authentication or pre-authentication (Kerberos).
    - Class Name (class_name) [Optional]: The event class name: Authentication.
    - Class ID (class_uid) [Required]: The unique identifier of a class.
    - Count (count) [Optional]: The number of times that events in the same logical group occurred during the event Start Time to End Time period.
    - Destination Endpoint (dst_endpoint) [Recommended]: The endpoint to which the authentication was targeted.
    - Duration (duration) [Optional]: The event duration or aggregate time, the amount of time the event covers from start_time to end_time in milliseconds.
    - End Time (end_time) [Optional]: The end time of a time period, or the time of the most recent event included in the aggregate event.
    - Is Cleartext (is_cleartext) [Optional]: Indicates whether the credentials were passed in clear text.
    - Is MFA (is_mfa) [Recommended]: Indicates whether Multi Factor Authentication was used during authentication.
    - Is New Logon (is_new_logon) [Optional]: Indicates logon is from a device not seen before or a first time account logon.
    - Is Remote (is_remote) [Recommended]: The attempted authentication is over a remote connection.
    - Logon Process (logon_process) [Optional]: The trusted process that validated the authentication credentials.
    - Logon Type (logon_type) [Recommended]: The logon type, normalized to the caption of the logon_type_id value.
    - Logon Type ID (logon_type_id) [Recommended]: The normalized logon type identifier.
    - Service (service) [Recommended]: The service or gateway to which the user or process is being authenticated.
    - Session (session) [Recommended]: The authenticated user or service session.
    - Source Endpoint (src_endpoint) [Recommended]: Details about the source of the IAM activity.
    - Start Time (start_time) [Optional]: The start time of a time period, or the time of the least recent event included in the aggregate event.
    - Status (status) [Recommended]: The event status, normalized to the caption of the status_id value.
    - Status Code (status_code) [Recommended]: The event status code, as reported by the event source.
    - Status Detail (status_detail) [Recommended]: The details about the authentication request.
    - Status ID (status_id) [Recommended]: The normalized identifier of the event status.
    - Time (time) [Required]: The normalized event occurrence time or the finding creation time.
    - Timezone Offset (timezone_offset) [Recommended]: The number of minutes that the reported event time is ahead or behind UTC.
    - Type Name (type_name) [Optional]: The event/finding type name, as defined by the type_uid.
    - Type ID (type_uid) [Required]: The event/finding type ID.
    - User (user) [Required]: The subject (user/role or account) to authenticate.
    """

    # Required fields
    activity_id: AuthenticationActivityID
    category_uid: int = IAMCategoryUID.IdentityAndAccessManagement.value
    class_uid: int = AuthenticationClassUID.Authentication.value
    metadata: Metadata
    severity_id: SeverityID
    time: int
    type_uid: AuthenticationTypeUID

    # Optional/Recommended fields
    activity_name: Optional[str]
    actor: Optional[Actor]
    auth_factors: Optional[list[AuthenticationFactor]]
    auth_protocol: Optional[str]
    auth_protocol_id: Optional[AuthProtocolID]
    authentication_token: Optional[AuthenticationToken]
    category_name: Optional[str] = "Identity & Access Management"
    certificate: Optional[str]
    class_name: Optional[str] = "Authentication"
    count: Optional[int]
    dst_endpoint: Optional[NetworkEndpoint]
    duration: Optional[int]
    end_time: Optional[int]
    end_time_dt: Optional[datetime]
    enrichments: Optional[list[Enrichment]]
    is_cleartext: Optional[bool]
    is_mfa: Optional[bool]
    is_new_logon: Optional[bool]
    is_remote: Optional[bool]
    logon_process: Optional[Process]
    logon_type: Optional[str]
    logon_type_id: Optional[LogonTypeID]
    message: Optional[str]
    observables: Optional[list[Observable]]
    raw_data: Optional[str]
    service: Optional[Service]
    session: Optional[Session]
    severity: Optional[str]
    src_endpoint: Optional[NetworkEndpoint]
    start_time: Optional[int]
    start_time_dt: Optional[datetime]
    status: Optional[str]
    status_code: Optional[str]
    status_detail: Optional[str]
    status_id: Optional[StatusID]
    time_dt: Optional[datetime]
    timezone_offset: Optional[int]
    type_name: Optional[str]
    unmapped: Optional[object]
    user: Optional[User]