from enum import IntEnum


class AuthenticationClassUID(IntEnum):
    """
    The unique identifier of the Authentication class.
    """
    
    Authentication = 3002
    """Authentication events report authentication session activities, including user attempts to log on or log off, regardless of success, as well as other key stages within the authentication process. These events are typically generated by authentication services, such as Kerberos, OIDC, or SAML, and may include information about the user, the authentication method used, and the status of the authentication attempt."""
